# Generated by Django 5.2.1 on 2025-06-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_textopresentacion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmpresaTrabajada",
        ),
    ]
