# Generated by Django 5.2.1 on 2025-09-03 15:38

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_parrafo_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción breve que aparecerá en el listado del blog')),
                ('imagen_portada', models.ImageField(blank=True, help_text='Imagen principal de la entrada', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='EntradaBlog/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=False, help_text='¿Está publicada la entrada?')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente)', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Entrada de Blog',
                'verbose_name_plural': 'Entradas de Blog',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='parrafo',
            name='entrada_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parrafos', to='app.entradablog'),
        ),
    ]
