# Generated by Django 5.2.1 on 2025-10-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_entradablog_parrafo_entrada_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradablog',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Descripción breve en inglés', null=True, verbose_name='Descripción (English)'),
        ),
        migrations.AddField(
            model_name='entradablog',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título (English)'),
        ),
        migrations.AddField(
            model_name='parrafo',
            name='contenido_en',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido (English)'),
        ),
        migrations.AddField(
            model_name='parrafo',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título (English)'),
        ),
        migrations.AddField(
            model_name='proyectofinalizado',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (English)'),
        ),
        migrations.AddField(
            model_name='proyectofinalizado',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título (English)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (English)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título (English)'),
        ),
        migrations.AddField(
            model_name='textopresentacion',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (English)'),
        ),
        migrations.AddField(
            model_name='textopresentacion',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título (English)'),
        ),
    ]
